# Generated by Django 3.2.6 on 2021-09-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact_num', models.CharField(max_length=13)),
                ('year_hired', models.DateField()),
                ('hours_worked', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('hours_late', models.IntegerField()),
                ('days_days', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.salary')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employer')),
            ],
        ),
    ]
