# Generated by Django 3.2.6 on 2021-09-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0002_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='days_days',
            new_name='days_absent',
        ),
    ]
