# Generated by Django 3.2.6 on 2021-09-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0003_rename_days_days_employee_days_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
