# Generated by Django 3.2.6 on 2021-09-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0004_auto_20210914_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employee'),
        ),
    ]
