# Generated by Django 3.2.6 on 2021-09-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0007_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
