# Generated by Django 3.2.6 on 2021-09-14 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0008_auto_20210914_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact_num', models.CharField(max_length=13)),
                ('year_hired', models.DateField()),
                ('hours_worked', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('hours_late', models.IntegerField()),
                ('days_absent', models.IntegerField()),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employee')),
            ],
        ),
    ]
