# Generated by Django 3.2.6 on 2021-09-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0009_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days_absent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_late',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year_hired',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_num',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAttendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_hired', models.DateField()),
                ('hours_worked', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('hours_late', models.IntegerField()),
                ('days_absent', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employee')),
            ],
        ),
    ]
