# Generated by Django 3.2.6 on 2021-09-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0010_auto_20210923_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendace',
            name='year_hired',
        ),
    ]
