# Generated by Django 3.2.7 on 2021-09-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0011_remove_employeeattendace_year_hired'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.city'),
        ),
    ]
