# Generated by Django 3.2.7 on 2021-09-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0012_auto_20210929_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='city',
            new_name='city_id',
        ),
    ]
