# Generated by Django 3.2.7 on 2021-09-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0013_rename_city_employee_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='city',
        ),
        migrations.AddField(
            model_name='employer',
            name='city_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.city'),
            preserve_default=False,
        ),
    ]
