# Generated by Django 3.2.7 on 2021-10-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0015_employee_year_hired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendace',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeAttendace',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
