# Generated by Django 3.2.7 on 2021-10-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanagement', '0016_auto_20211006_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_num', models.CharField(max_length=20)),
                ('year_hired', models.DateTimeField(blank=True, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.city')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('hours_late', models.IntegerField()),
                ('days_absent', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarymanagement.employee')),
            ],
        ),
    ]
